import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  section: { padding: 16 },
  title: { fontSize: 26, fontWeight: 'bold', color: '#1976d2' },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#222' },
  
  // Fixed Header Styles
  fixedHeader: {
    backgroundColor: '#fff',
    marginTop: 5,
    paddingTop: Platform.OS === 'ios' ? 60 : 16,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    } : {
      elevation: 4,
    }),
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1976d2',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  
  carouselContainer: { marginBottom: 18, alignItems: 'center' },
  carouselItem: { width: 325, backgroundColor: '#e3f2fd', borderRadius: 12, padding: 18, marginHorizontal: 10, alignItems: 'center' },
  carouselTitle: { fontSize: 18, fontWeight: 'bold', color: '#1976d2' },
  carouselText: { fontSize: 14, color: '#333', textAlign: 'center' },
  carouselDotRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 8 },
  carouselDot: { backgroundColor: '#1976d2', borderRadius: 8, marginHorizontal: 4 },
  
  performanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  performanceCard: {
    width: '48%',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(25, 118, 210, 0.2)',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    } : {
      elevation: 2,
    }),
  },
  performanceNumber: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1976d2',
  },
  performanceLabel: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabActive: {
    backgroundColor: '#fff',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    } : {
      elevation: 2,
    }),
  },
  tabText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#1976d2',
    fontWeight: 'bold',
  },
  
  categoryCardLarge: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(25, 118, 210, 0.2)',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    } : {
      elevation: 2,
    }),
  },
  categoryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#e3f2fd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  categoryCardContent: {
    flex: 1,
  },
  categoryCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 4,
  },
  categoryCardSubtitle: {
    fontSize: 13,
    color: '#666',
  },
  categoryProgressContainer: {
    marginTop: 8,
  },
  categoryProgressBar: {
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 6,
  },
  categoryProgressFill: {
    height: '100%',
    backgroundColor: '#1976d2',
    borderRadius: 4,
  },
  categoryProgressText: {
    fontSize: 12,
    color: '#666',
  },
  
  continueLearningBtn: {
    backgroundColor: '#43a047',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {
      elevation: 3,
    }),
  },
  continueLearningText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  quickPracticeBtn: {
    backgroundColor: '#43a047',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    } : {
      elevation: 6,
    }),
  },
  quickPracticeTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  quickPracticeSubtitle: {
    color: '#fff',
    fontSize: 13,
    marginTop: 2,
    opacity: 0.9,
  },
  
  startFlashcardsBtn: {
    backgroundColor: '#1976d2',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {
      elevation: 3,
    }),
  },
  startFlashcardsBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  
  signCardDetail: {
    flexDirection: 'row',
    backgroundColor: '#f9f9f9',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  signImgDetail: {
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: '#fff',
  },
  signCardDetailContent: {
    flex: 1,
    justifyContent: 'center',
  },
  signImageWrapper: {
    position: 'relative',
  },
  masteredBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#FFD700',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  signCategoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: '#e3f2fd',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  signCategoryText: {
    fontSize: 12,
    color: '#1976d2',
    marginLeft: 4,
    fontWeight: '600',
  },
  signProgressInfo: {
    marginTop: 8,
    backgroundColor: '#fff3e0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  signProgressText: {
    fontSize: 11,
    color: '#e65100',
    fontWeight: '600',
  },
  signCardDetailTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1976d2',
    marginBottom: 6,
  },
  signCardDetailDesc: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  
  startBtn: { backgroundColor: '#43a047', borderRadius: 18, paddingVertical: 12, alignItems: 'center', marginTop: 10 },
  startBtnText: { color: '#fff', fontWeight: 'bold' },

  progressBarContainer: { height: 24, backgroundColor: '#eee', borderRadius: 12, overflow: 'hidden', marginBottom: 10, width: '100%' },
  progressBarFill: { position: 'absolute', left: 0, top: 0, bottom: 0, backgroundColor: '#1976d2' },
  progressBarText: { textAlign: 'center', fontWeight: 'bold', color: '#555', lineHeight: 24 },

  topicCard: { backgroundColor: '#e3f2fd', borderRadius: 10, marginBottom: 10 },
  topicHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12 },
  topicTitle: { fontWeight: 'bold', color: '#1976d2', fontSize: 16 },

  // Modern Chapter Cards (Option 2)
  modernChapterCard: {
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    } : {
      elevation: 6,
    }),
  },
  modernChapterGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modernChapterGradientEnd: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.6,
  },
  modernCompletedBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 4,
    zIndex: 10,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    } : {
      elevation: 4,
    }),
  },
  modernChapterContent: {
    padding: 24,
  },
  modernChapterBadge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  modernChapterBadgeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  modernChapterTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    lineHeight: 28,
  },
  modernLastAccessed: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: 16,
    fontStyle: 'italic',
  },
  modernChapterButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  modernChapterButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
  },

  // Enhanced Chapter Cards (All Features)
  enhancedChapterCard: {
    width: '100%',
    borderRadius: 18,
    marginBottom: 18,
    overflow: 'hidden',
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
    } : {
      elevation: 8,
    }),
  },
  enhancedChapterGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  enhancedChapterGradientEnd: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.7,
  },
  enhancedCompletedBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 4,
    zIndex: 10,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    } : {
      elevation: 5,
    }),
  },
  enhancedChapterContent: {
    padding: 16,
  },
  enhancedChapterTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  enhancedChapterBadge: {
    height: 44,
    width: 42,
    borderRadius: 22,
    backgroundColor: 'rgba(25, 118, 210, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(25, 118, 210, 0.3)',
  },
  enhancedChapterBadgeText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1976d2',
  },
  enhancedChapterTitle: {
    marginLeft: 10,
    marginRight: 6,
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1976d2',
    lineHeight: 22,
  },
  enhancedMetaRow: {
    flexDirection: 'row',
    marginBottom: 10,
    flexWrap: 'wrap',
  },
  enhancedMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 4,
  },
  enhancedMetaText: {
    fontSize: 11,
    color: '#666',
    marginLeft: 4,
    fontWeight: '600',
  },
  enhancedProgressContainer: {
    marginBottom: 12,
  },
  enhancedProgressBar: {
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 4,
  },
  enhancedProgressFill: {
    height: '100%',
    backgroundColor: '#fff',
    borderRadius: 4,
  },
  enhancedProgressText: {
    fontSize: 10,
    color: '#666',
    fontWeight: '700',
  },
  enhancedLastAccessed: {
    fontSize: 10,
    color: '#666',
    marginBottom: 10,
    fontStyle: 'italic',
  },
  enhancedActionButton: {
    backgroundColor: '#43a047',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    marginTop: 4,
  },
  enhancedActionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 6,
  },

  // Chapter Grid Layout
  chapterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },

  lessonCardLarge: { padding: 14, borderRadius: 8, backgroundColor: '#fff', borderWidth: 1, borderColor: '#f0f0f0', marginBottom: 10 },
  lessonTitleLarge: { fontSize: 16, color: '#222' },

  lessonReaderTitle: { fontSize: 22, fontWeight: 'bold', color: '#1976d2', marginBottom: 12 },
  lessonReaderText: { fontSize: 15, color: '#444', marginBottom: 14 },

  quizBtn: { backgroundColor: '#43a047', padding: 12, borderRadius: 10, alignItems: 'center', marginTop: 8 },
  quizBtnText: { color: '#fff', fontWeight: 'bold' },

  quizOption: { backgroundColor: '#e3f2fd', padding: 10, borderRadius: 8, marginTop: 8 },
  quizOptionCorrect: { backgroundColor: '#c8e6c9' },
  quizOptionIncorrect: { backgroundColor: '#ffcdd2' },

  mockTestCard: { backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 16, borderWidth: 1, borderColor: '#e0e0e0', ...(Platform.OS === 'ios' ? { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 } : { elevation: 2 }) },
  mockTestTitle: { fontWeight: 'bold', color: '#1976d2', fontSize: 18 },
  mockTestCardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  mockTestNumberBadge: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#1976d2', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  mockTestNumberText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  mockTestCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#e0e0e0' },
  mockTestInfoRow: { flexDirection: 'row', alignItems: 'center' },
  startMockTestBtn: { backgroundColor: '#43a047', flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20 },
  startMockTestBtnText: { color: '#fff', fontWeight: 'bold', marginRight: 4 },
  mockTestInfoCard: { backgroundColor: '#e3f2fd', padding: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  mockTestInfoText: { marginLeft: 8, color: '#1976d2', fontWeight: '600', flex: 1 },
  
  chapterTestBtn: { backgroundColor: '#43a047', borderRadius: 12, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 12, ...(Platform.OS === 'ios' ? { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4 } : { elevation: 3 }) },
  chapterTestBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold', marginLeft: 8 },

  testSessionContainer: { flex: 1, backgroundColor: '#fff' },
  testSessionHeader: { backgroundColor: '#f5f5f5', padding: 16, borderBottomWidth: 1, borderBottomColor: '#e0e0e0' },
  testSessionTitle: { fontSize: 18, fontWeight: 'bold', color: '#1976d2', marginBottom: 8 },
  testProgressBar: { height: 8, backgroundColor: '#e0e0e0', borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
  testProgressFill: { height: '100%', backgroundColor: '#43a047', borderRadius: 4 },
  testSessionProgress: { fontSize: 14, color: '#666', textAlign: 'center' },
  testQuestion: { fontSize: 18, fontWeight: '600', color: '#222', padding: 16, lineHeight: 26 },
  testOption: { backgroundColor: '#f9f9f9', padding: 16, marginHorizontal: 16, marginBottom: 12, borderRadius: 12, borderWidth: 2, borderColor: '#e0e0e0' },
  testOptionSelected: { backgroundColor: '#e3f2fd', borderColor: '#1976d2' },
  testOptionContent: { flexDirection: 'row', alignItems: 'center' },
  testOptionCircle: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#999', marginRight: 12, alignItems: 'center', justifyContent: 'center' },
  testOptionCircleSelected: { borderColor: '#1976d2' },
  testOptionCircleInner: { width: 14, height: 14, borderRadius: 7, backgroundColor: '#1976d2' },
  testOptionText: { fontSize: 16, color: '#222', flex: 1, lineHeight: 22 },
  
  testReviewSection: { paddingHorizontal: 16 },
  testReviewTitle: { fontSize: 20, fontWeight: 'bold', color: '#222', marginBottom: 16 },
  reviewQuestionCard: { backgroundColor: '#f9f9f9', borderRadius: 12, padding: 16, marginBottom: 12, borderLeftWidth: 4 },
  reviewCorrect: { borderLeftColor: '#43a047', backgroundColor: '#f1f8f4' },
  reviewIncorrect: { borderLeftColor: '#e53935', backgroundColor: '#fef5f5' },
  reviewQuestionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  reviewQuestionNumber: { fontSize: 16, fontWeight: 'bold', color: '#1976d2' },
  reviewQuestionText: { fontSize: 15, color: '#222', marginBottom: 12, lineHeight: 22 },
  reviewAnswerBlock: { backgroundColor: '#fff', padding: 10, borderRadius: 8, marginTop: 8 },
  reviewYourAnswer: { fontSize: 14, color: '#e53935' },
  reviewCorrectAnswer: { fontSize: 14, color: '#43a047', fontWeight: '600' },

  lessonSignsSection: { marginTop: 24, marginBottom: 16, padding: 16, backgroundColor: '#f5f5f5', borderRadius: 12 },
  lessonSignsSectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#1976d2', marginBottom: 16 },
  lessonSignCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#e0e0e0', ...(Platform.OS === 'ios' ? { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2 } : { elevation: 1 }) },
  lessonSignImageContainer: { marginRight: 12 },
  lessonSignImage: { width: 80, height: 80, borderRadius: 8 },
  lessonSignContent: { flex: 1, justifyContent: 'center' },
  lessonSignTitle: { fontSize: 16, fontWeight: 'bold', color: '#1976d2', marginBottom: 6 },
  lessonSignDescription: { fontSize: 14, color: '#666', lineHeight: 20 },

  quizContainer: { flex: 1, backgroundColor: '#fff' },
  quizProgressContainer: { backgroundColor: '#f5f5f5', padding: 16, borderBottomWidth: 1, borderBottomColor: '#e0e0e0' },
  quizProgressBar: { height: 8, backgroundColor: '#e0e0e0', borderRadius: 4, overflow: 'hidden', marginBottom: 8 },
  quizProgressFill: { height: '100%', backgroundColor: '#43a047', borderRadius: 4 },
  quizProgressText: { fontSize: 14, color: '#666', textAlign: 'center', fontWeight: '600' },
  quizContent: { padding: 20, paddingBottom: 40 },
  quizImageContainer: { alignItems: 'center', marginBottom: 24, backgroundColor: '#f9f9f9', borderRadius: 16, padding: 20 },
  quizImage: { width: 200, height: 200, borderRadius: 12 },
  quizQuestion: { fontSize: 22, fontWeight: 'bold', color: '#1976d2', textAlign: 'center', marginBottom: 24 },
  quizOptionsContainer: { marginBottom: 20 },
  quizOptionText: { fontSize: 16, color: '#222', flex: 1 },
  feedbackContainer: { borderRadius: 12, padding: 16, marginTop: 16, flexDirection: 'row', alignItems: 'flex-start' },
  feedbackCorrect: { backgroundColor: '#e8f5e9', borderWidth: 1, borderColor: '#43a047' },
  feedbackIncorrect: { backgroundColor: '#ffebee', borderWidth: 1, borderColor: '#e53935' },
  feedbackTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  feedbackText: { fontSize: 14, color: '#666', marginBottom: 8 },
  feedbackDescription: { fontSize: 13, color: '#666', fontStyle: 'italic', marginTop: 4 },
  resultsStatsContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  resultStatCard: { flex: 1, borderRadius: 12, padding: 16, alignItems: 'center', marginHorizontal: 4, ...(Platform.OS === 'ios' ? { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 } : { elevation: 2 }) },
  resultStatNumber: { fontSize: 32, fontWeight: 'bold', color: '#222', marginTop: 8 },
  resultStatLabel: { fontSize: 13, color: '#666', marginTop: 4 },
  encouragementBox: { backgroundColor: '#e8f5e9', borderRadius: 12, padding: 16, marginTop: 8, borderWidth: 1, borderColor: '#43a047' },
  encouragementText: { fontSize: 16, color: '#2e7d32', textAlign: 'center', fontWeight: '600' },
  nextButton: { backgroundColor: '#1976d2', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, paddingHorizontal: 24, borderRadius: 12, marginTop: 20, ...(Platform.OS === 'ios' ? { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4 } : { elevation: 3 }) },
  nextButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginRight: 8 },
});